/**
 * Marines tree category definitions.
 * Used by /marines landing page (alphabetical 21-card grid) and category indexes.
 *
 * The slug field becomes the URL segment: /marines/[slug]/[page-slug]
 * Existing MDX files use the slug as their `topic` field value.
 */
export interface MarinesCategory {
  slug: string;
  label: string;
  shortLabel: string;
  description: string;
  /** Lucide icon name. */
  icon:
    | "Trophy"
    | "Home"
    | "Utensils"
    | "DollarSign"
    | "Plane"
    | "Users"
    | "FileText"
    | "Heart"
    | "LifeBuoy"
    | "LogIn"
    | "CalendarDays"
    | "Heart2"
    | "AlertCircle"
    | "Truck"
    | "TrendingUp"
    | "ClipboardList"
    | "RefreshCcw"
    | "LogOut"
    | "Star"
    | "Briefcase"
    | "Shirt"
    | "GraduationCap"
    | "CreditCard";
  /**
   * "container": the topic has multiple sub-pages. /marines/[slug] renders an
   *   index of those sub-pages, and each sub-page lives at /marines/[slug]/[page-slug].
   * "leaf": the topic is a single wiki page. /marines/[slug] renders the
   *   single MDX file (whose slug equals the topic slug). No sub-pages.
   *
   * Defaults to "container" if unset.
   */
  pageType?: "container" | "leaf";
}

export const MARINES_CATEGORIES: MarinesCategory[] = [
  {
    slug: "ai-and-data-management-training",
    label: "AI and Data Management Training",
    shortLabel: "AI Training",
    description: "Available training beyond the Basic AI Course. MarineNet Skillsoft and Percipio. Digital University (USAF). Joint Knowledge Online (JKO). GSA Centers of Excellence. II MEF Basic Data Literacy. US Navy Community College (USNCC). Naval Postgraduate School (NPS) AI for Military Use. Per MARADMIN 270/25.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "ai-ethical-use",
    label: "AI Ethical Use",
    shortLabel: "AI Ethics",
    description: "Responsible AI principles per DoD Responsible AI Strategy. Six tenets of responsible AI. COMMSTRAT-specific guidance per MARADMIN 635/24 (supersedes 602/24). No photo-realistic imagery or video for public dissemination. Human oversight. AI annotation in caption and metadata. Per MCO 5231.4.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "ai-fellowship-programs",
    label: "AI Fellowship Programs (NPS)",
    shortLabel: "AI Fellowship",
    description: "Naval Postgraduate School (NPS) AI Fellowship per MARADMIN 135/26. 5-month project-based fellowship. Eligibility O1-O5, E4-E8, CWO 1-5, GS-5 to GS-14. Approximately $5K TAD. Three TAD trips to Monterey. Capstone research paper requirement.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "ai-governance-and-approval",
    label: "AI Governance and Approval",
    shortLabel: "AI Governance",
    description: "DC I (Deputy Commandant for Information) centralized governance authority. Marine Corps Service Data Officer (MC SDO) policy lead. Functional Data Working Group (FDWG) and Artificial Intelligence Working Group (AIWG). Approval required for new GenAI capabilities. Per MCO 5231.4.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "ai-overview",
    label: "AI Overview and Authorities",
    shortLabel: "AI Overview",
    description: "The framework. MCO 5231.4 (Marine Corps Data and Artificial Intelligence). USMC AI Implementation Plan. NAVMC 3000.1. DC I as service lead. Service Data Office (SDO). MARADMIN ecosystem. VAULTIS standard. Responsible AI principles. Emerging and Disruptive Technologies (EDT).",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "basic-ai-course",
    label: "Basic AI Course (Mandatory)",
    shortLabel: "Basic AI Course",
    description: "Mandatory training per MARADMIN 214/26. All Active Duty and Reserve Marines (officer and enlisted) complete NLT 31 December 2026. Course code CDETBAIC01 on MCELE (formerly MarineNet). 45 minutes. One-time requirement. Tracked in MCTFS Basic Training Record (BTR) via MOL.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "camogpt-and-approved-ai-tools",
    label: "CamoGPT and Other Approved AI Tools",
    shortLabel: "CamoGPT",
    description: "Authorized AI tools beyond GenAI.mil. CamoGPT and other GenAI systems meeting government system requirements. NIPRGPT sunsetting. Coordination with DC I for new tool approval. Per MARADMIN 018/26.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "data-and-ai-workforce-roles",
    label: "Data and AI Workforce Roles",
    shortLabel: "Workforce Roles",
    description: "14 Data Workforce Roles (MC SDO, ADO, Data Steward, Data Custodian, CDAO, Data Producer, System Owner, Data Architect, Analytic Developer, Data Analytics Specialist, Data Engineer, Data Modeler, Data Scientist, Data Security Engineer). 7 AI Workforce Roles (AI Researcher, AI/ML Engineer, T&E Engineer, Deployment Engineer, AI Technician, Product Owner, UI/UX). Per MCO 5231.4 Enclosures 2 and 3.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "genai-mil-enterprise-platform",
    label: "GenAI.mil Enterprise Platform",
    shortLabel: "GenAI.mil",
    description: "Marine Corps enterprise generative AI platform at genai.mil. Per MARADMIN 018/26 (supersedes MARADMIN 496/24). Authorized for CUI on government-furnished equipment. NOT approved for PII, PHI, or classified. Conversational chat, file upload (PDF/DOCX/TXT), RAG, secure web grounding, deep research. NIPRGPT sunsetting.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "practical-ai-use",
    label: "Practical AI Use for Marines",
    shortLabel: "Practical AI Use",
    description: "Day-to-day AI use. Verifying AI outputs. User responsibility and accountability. Common use cases. CUI handling. Annotation requirements. Limitations of GenAI. When to use AI vs conventional methods. Risk-informed experimentation per MARADMIN 214/26.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "semper-admin-ai-field-manual",
    label: "Semper Admin AI Field Manual",
    shortLabel: "Field Manual",
    description: "The Semper Admin AI Field Manual v3.0. 100 prompts across 10 categories. 53 pages. The operational AI prompt standard for USMC administration. Built by Marines for Marines. Five pillars: Accuracy, Verification, Accountability, Designed for the Fight, Open and Improving. CUI ceiling. Download PDF or visit github.com/semperadmin.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "awards-overview",
    label: "Awards Overview and Authorities",
    shortLabel: "Awards Overview",
    description: "The framework. MCO P1650.19J Marine Corps Awards Manual. Submission process. Award authorities. OMPF entry verification. Common failure points.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "campaign-and-service-medals",
    label: "Campaign, Expeditionary, and Service Medals (CE&S)",
    shortLabel: "Campaign Medals",
    description: "Campaign medals (NDSM, GWOTSM, GWOTEM, ICM, ACM). Service medals. Eligibility windows per executive order or DoD authorization. OMPF documentation.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "combat-action-ribbon",
    label: "Combat Action Ribbon (CAR)",
    shortLabel: "CAR",
    description: "Eligibility for active engagement with hostile force. Recommendation by chain of command. Documentation requirements. Per MCO P1650.19J.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "foreign-awards",
    label: "Foreign Awards",
    shortLabel: "Foreign Awards",
    description: "Foreign government awards to U.S. service members. Acceptance authorization through DoD. Wear authorization. OMPF entry. Per MCO P1650.19J.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "joint-service-awards",
    label: "Joint Service Awards",
    shortLabel: "Joint Awards",
    description: "Joint Meritorious Service Medal, Joint Service Commendation Medal, Joint Service Achievement Medal. Eligibility on joint duty assignments. Per DoDM 1348.33.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "marksmanship-badges",
    label: "Marksmanship Badges (Rifle and Pistol)",
    shortLabel: "Marksmanship",
    description: "Rifle and pistol marksmanship badges. Annual qualification scoring. Expert, Sharpshooter, Marksman tiers. Wear and OMPF documentation.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "movsm",
    label: "Military Outstanding Volunteer Service Medal (MOVSM)",
    shortLabel: "MOVSM",
    description: "Recognition for outstanding sustained voluntary service to the civilian community. 3-year period requirement. Documentation by sponsor. Per DoD policy.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "pcs-and-awards-timing",
    label: "PCS and Awards Timing",
    shortLabel: "PCS Awards",
    description: "End-of-tour awards. Submission timeline before PCS departure. Recommendation drafting. PCS award gaps and recovery. Per MCO P1650.19J.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "personal-military-decorations",
    label: "Personal Military Decorations (PMDs) - The Hierarchy",
    shortLabel: "Personal Decorations",
    description: "Medal of Honor through Navy and Marine Corps Achievement Medal. Hierarchy and precedence. Combat versus non-combat distinctions. Award authority levels.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "purple-heart",
    label: "Purple Heart",
    shortLabel: "Purple Heart",
    description: "Eligibility for wounds or death from enemy action. Submission process. Documentation requirements. Special considerations. Per Title 10 USC and MCO P1650.19J.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "receiving-an-award",
    label: "Receiving an Award (Ceremony, Citation, Certificate)",
    shortLabel: "Receiving",
    description: "Award presentation ceremony. Citation and certificate handling. Personal copies and originals. OMPF documentation. Family attendance.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "retirement-awards-and-dd214",
    label: "Retirement Awards and DD-214",
    shortLabel: "Retirement Awards",
    description: "End-of-career retirement awards. Recommendation timing before retirement ceremony. DD-214 award entry verification. Common errors at separation.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "unit-awards",
    label: "Unit Awards You Participate In",
    shortLabel: "Unit Awards",
    description: "Presidential Unit Citation, Navy Unit Commendation, Meritorious Unit Commendation, Navy Meritorious Unit Commendation. Eligibility through unit assignment during award period.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "verifying-your-awards",
    label: "Verifying Your Awards in OMPF",
    shortLabel: "Verifying Awards",
    description: "OMPF awards section review. Marine Online (MOL) verification. Missing or incorrect entries. Submission of corrections through S-1.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "wearing-your-awards",
    label: "Wearing Your Awards (Precedence and Devices)",
    shortLabel: "Wearing Awards",
    description: "Precedence of medals and ribbons on uniform. Devices (stars, oak leaves, V device, etc.). Mounting and proper wear. Per MCO P1020.34H Marine Corps Uniform Regulations.",
    icon: "Trophy",
    pageType: "leaf",
  },
  {
    slug: "bah",
    label: "BAH (Housing Allowance)",
    shortLabel: "BAH",
    description: "Rates, dependent status, PCS transitions, OHA, common errors.",
    icon: "Home",
    pageType: "leaf",
  },
  {
    slug: "bas",
    label: "BAS (Food Allowance)",
    shortLabel: "BAS",
    description: "Officer vs enlisted, meal cards, sep rats, field conditions.",
    icon: "Utensils",
    pageType: "leaf",
  },
  {
    slug: "basic-needs-allowance",
    label: "Basic Needs Allowance (BNA)",
    shortLabel: "BNA",
    description: "Monthly allowance for active-duty Marines with dependents whose income falls below 150 percent FPG (200 percent in high-cost areas). Per 37 U.S.C. 402b, NDAA FY22, DoDI 1341.16, and MARADMIN 037/23. Effective 1 January 2023.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "basic-pay",
    label: "Basic Pay",
    shortLabel: "Basic Pay",
    description: "Pay tables, increases, first paycheck, school and training pay.",
    icon: "DollarSign",
    pageType: "leaf",
  },
  {
    slug: "hostile-fire-and-imminent-danger-pay",
    label: "Hostile Fire Pay and Imminent Danger Pay (HFP/IDP)",
    shortLabel: "HFP/IDP",
    description: "$225/month for combat zone or hostile fire area service. HFP full month for any qualifying event. IDP prorated daily.",
    icon: "AlertCircle",
    pageType: "leaf",
  },
  {
    slug: "family-separation-allowance",
    label: "Family Separation Allowance (FSA)",
    shortLabel: "FSA",
    description: "$300/month for involuntary separation 30+ days (effective 18 December 2025 per MARADMIN 150/26 and NDAA FY 2026, increased from $250). FSA-R, FSA-S, FSA-T types. DD Form 1561 substantiation.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "combat-zone-tax-exclusion",
    label: "Combat Zone Tax Exclusion (CZTE)",
    shortLabel: "CZTE",
    description: "Federal tax exclusion for CZ service. Full for enlisted/warrant. Officer cap at senior enlisted rate plus HFP/IDP.",
    icon: "FileText",
    pageType: "leaf",
  },
  {
    slug: "apes-and-fitrep-administration",
    label: "A-PES and FITREP Administration",
    shortLabel: "A-PES and Admin",
    description: "Automated Performance Evaluation System (A-PES) access via Marine Online. MMPB-23 sections (Policy/Compliance/Corrections, Processing/Audit, JEPES). Administrative corrections via Appendix G. Date gaps and overlaps (30-day threshold). Admin fillers. Commander's Timeliness Report (CTR). IGMC FA 1610 inspections. Submission timelines (30 days normal, 60 days adverse).",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "academic-fitreps",
    label: "Academic FITREPs (PME and GEP)",
    shortLabel: "Academic FITREPs",
    description: "Per MARADMIN 412/20. Officers in resident PME (Career, Intermediate, Advanced Intermediate, Top Level) and Graduate Education Programs (NPS, AFIT, NDU, Law, etc.). Section A type 'A' for academic. Sections D-H not observed. RS/RO profile NOT impacted.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "performance-evaluation-overview",
    label: "Performance Evaluation Overview and Authorities",
    shortLabel: "PES Overview",
    description: "Unified Performance Evaluation framework. MCO 1610.7B (FITREPs), MCO 1616.1 (JEPES), MARADMIN 066/26 (body composition reporting). HQMC PES, fitness report cycles, the MRO/RS/RO chain.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "fitrep-sections-and-marking",
    label: "FITREP Sections and Marking",
    shortLabel: "FITREP Sections",
    description: "Section-by-section walkthrough of MCO 1610.7B FITREP Sections A through K. Billet description, performance attributes, comparative assessment, marking philosophy, MRO acknowledgment.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "fitrep-reporting-cycle",
    label: "FITREP Reporting Cycle and Report Types",
    shortLabel: "FITREP Cycle",
    description: "Annual reports, Change of RS, Change of RO, Change of Duty, Change of Status, Reserve Component reporting cycle, special reports. Per MCO 1610.7B.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "reporting-senior-and-reviewing-officer-roles",
    label: "Reporting Senior and Reviewing Officer Roles",
    shortLabel: "RS and RO Roles",
    description: "RS responsibilities (initial counseling, mid-period counseling, marking). RO responsibilities (concurrence, non-concurrence, third officer sighter triggers). Profile management. Per MCO 1610.7B.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "adverse-fitreps",
    label: "Adverse FITREPs and Referred Reports",
    shortLabel: "Adverse FITREPs",
    description: "Adverse marks, referred reports, MRO addendum opportunity, RS counseling requirements. ABCD adjudication and quality control. Per MCO 1610.7B.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "body-composition-reporting",
    label: "Body Composition Reporting on Performance Evaluations",
    shortLabel: "Body Comp Reporting",
    description: "Per MARADMIN 066/26 effective 1 January 2026. WHtR methodology replaces height/weight. Five directed comments for Section A Item 8d-f. 000/blank entry rule. Incomplete BIA assessment treatment.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "fitrep-appeals-perb",
    label: "FITREP Appeals (PERB Process)",
    shortLabel: "FITREP Appeals",
    description: "Performance Evaluation Review Board appeals. Time limits, grounds for appeal, MRO petition format, supporting documentation, board adjudication. Per MCO 1610.7B Chapter 7.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "jepes-junior-enlisted",
    label: "JEPES (Junior Enlisted Performance Evaluation System)",
    shortLabel: "JEPES",
    description: "MCO 1616.1 framework for E-1 through E-4. Marking system, Reporting Officials, JEPES report types, transition from JEPES to FITREP framework on promotion to Sergeant.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "master-brief-sheet",
    label: "Master Brief Sheet (MBS)",
    shortLabel: "MBS",
    description: "Aggregate display of all FITREPs in the OMPF. Reading the MBS, common errors, verification before promotion or selection boards, the Reporting Senior Profile. Per MCO 1610.7B.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "legal-services-overview",
    label: "Legal Services Overview and How to Get Help",
    shortLabel: "Legal Services",
    description: "JAG offices, personal services attorneys, defense counsel, trial counsel, victim's counsel. When to seek help. Office hours. Per MCO 5800.16 Vol 1 and Vol 13.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "article-31-rights-and-investigations",
    label: "Article 31 Rights and Investigations",
    shortLabel: "Article 31 Rights",
    description: "UCMJ Article 31 rights against self-incrimination. Right to counsel during questioning. NCIS, CID, MP interactions. JAGMAN command investigations. Sources. UCMJ Article 31, JAGMAN.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "njp-non-judicial-punishment",
    label: "NJP (Non-Judicial Punishment)",
    shortLabel: "NJP",
    description: "Article 15 / Captain's Mast / Office Hours. Maximum punishments by grade and command level. Right to refuse and demand court-martial (unless attached to a vessel). Appeals. Per MCO 5800.16 Vol 6 and UCMJ Article 15.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "powers-of-attorney-and-wills",
    label: "Powers of Attorney and Wills",
    shortLabel: "POA and Wills",
    description: "General POA, Special POA, Limited POA, Durable POA. JAG-prepared wills. Living wills and advance medical directives. Pre-deployment legal preparation. Per MCO 5800.16 Vol 3.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "servicemembers-civil-relief-act",
    label: "Servicemembers Civil Relief Act (SCRA)",
    shortLabel: "SCRA",
    description: "Federal civilian-side protections. Lease termination on PCS or 90+ day deployment. 6% interest rate cap on pre-service obligations. Default judgment, mortgage, foreclosure, and eviction protections. Per 50 U.S.C. Chapter 50.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "family-law-for-marines",
    label: "Family Law for Marines",
    shortLabel: "Family Law",
    description: "Divorce, custody and visitation across PCS, child support garnishment via DFAS, family support requirements, Family Care Plans for single parents and dual-military couples. Per MCO 5800.16 Vol 3 and MCO 1740.13.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "article-138-and-ig-complaints",
    label: "Article 138 and IG Complaints",
    shortLabel: "Article 138 / IG",
    description: "Filing a complaint against a superior under Article 138 UCMJ. The 90-day timeline. Inspector General complaints. Whistleblower protections. Reprisal complaints. Per UCMJ Article 138 and MCO 5370.7.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "sexual-assault-reporting-svc",
    label: "Sexual Assault Reporting and Special Victims' Counsel",
    shortLabel: "SAPR and SVC",
    description: "Restricted vs Unrestricted reporting. SAPR program. Special Victims' Counsel (SVC) services. SAFE forensic exams. Article 6b UCMJ victim rights. Per DoDD 6495.01, MCO 1752.5C, UCMJ Article 6b.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "personal-property-claims",
    label: "Personal Property Claims",
    shortLabel: "Property Claims",
    description: "Filing claims for damaged or lost personal property during PCS. Limits and deadlines. Personnel Claims Act. JAGMAN claims procedures. Per MCO 5800.16 Vol 4 and JAGMAN.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "court-martial-process",
    label: "Court-Martial Process",
    shortLabel: "Court-Martial",
    description: "Summary, Special, and General courts-martial. Rights of the accused. Pretrial confinement. Plea agreements. Sentencing. Appeals (NMCCA, CAAF). Per MCO 5800.16 Vol 5 and UCMJ Articles 16-58.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "administrative-separation",
    label: "Administrative Separation",
    shortLabel: "Admin Separation",
    description: "Discharge characterizations (Honorable, General Under Honorable, OTH, BCD, Dishonorable). Voluntary vs involuntary separation. Show cause boards. Notification procedures. Effect on benefits. Per MCO 5800.16 Vol 8 and MARCORSEPMAN.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "foreign-jurisdiction-sofa",
    label: "Foreign Jurisdiction and SOFA",
    shortLabel: "SOFA",
    description: "Status of Forces Agreements. When U.S. has primary jurisdiction vs host nation. Common OCONUS legal concerns (Japan, Korea, Germany, etc.). Pre-departure legal briefings. What to do if arrested overseas. Per MCO 5800.16 Vol 16 and applicable SOFAs.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "joining-a-unit",
    label: "Joining a Unit (Inbound Reporting and Check-In)",
    shortLabel: "Joining",
    description: "Reporting endorsement, 24-hour to 30-day check-in milestones, sponsorship pickup, initial counseling, post-PCS pay actions, first 90 days. Per MCO 1300.8, MCO 1000.6, MCO 1320.11H, MCO 1610.7, and JTR Chapter 5.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "annual-leave",
    label: "Annual Leave",
    shortLabel: "Annual Leave",
    description: "2.5 days/month accrual, 30 days/year, 60-day FY carryover cap. Per MCO 1050.3J Chapter 2.",
    icon: "CalendarDays",
    pageType: "leaf",
  },
  {
    slug: "special-leave-accrual",
    label: "Special Leave Accrual (SLA)",
    shortLabel: "SLA",
    description: "Up to 30 days SLA on top of 60-day annual leave (90-day cap total). Qualifying duties, GO approval, FY+2 expiration. Per MARADMIN 188/25.",
    icon: "CalendarDays",
    pageType: "leaf",
  },
  {
    slug: "liberty-and-special-liberty",
    label: "Liberty and Special Liberty",
    shortLabel: "Liberty",
    description: "Local liberty boundaries, regular liberty, weekend liberty, 96/72-hour holiday liberty, liberty-leave combinations.",
    icon: "CalendarDays",
    pageType: "leaf",
  },
  {
    slug: "military-parental-leave-program",
    label: "Military Parental Leave Program (MPLP)",
    shortLabel: "MPLP",
    description: "Active Duty parental leave: 12 weeks (84 days) for primary/secondary caregivers, 6-week birth parent convalescent, 12-month usage window.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "reserve-parental-leave",
    label: "Reserve Component Parental Leave (RCPL)",
    shortLabel: "RCPL",
    description: "12 paid IDT periods for SELRES Marines after qualifying event (birth, adoption, foster). Max 2 per day. Per MARADMIN 191/26.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "reserve-maternity-leave",
    label: "Reserve Component Maternity Leave (RCML)",
    shortLabel: "RCML",
    description: "6-week postpartum convalescent (no IDT). Up to 6 paid IDT periods within 8-week post-birth window. Per MARADMIN 191/26.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "permissive-tad",
    label: "Permissive TAD (PTAD) and SkillBridge",
    shortLabel: "PTAD",
    description: "House Hunting (10 days), Transition PTAD, SkillBridge PTAD (90/120-day cap). Per MCO 1050.3J Chapter 5 and MARADMIN 625/24.",
    icon: "CalendarDays",
    pageType: "leaf",
  },
  {
    slug: "convalescent-leave",
    label: "Convalescent Leave (Sick Leave)",
    shortLabel: "Convalescent Leave",
    description: "Medical recovery leave. Not charged against accrued leave. 30-day initial period, extendable for surgery, injury, illness recovery.",
    icon: "Heart",
    pageType: "leaf",
  },
  {
    slug: "emergency-leave",
    label: "Emergency Leave",
    shortLabel: "Emergency Leave",
    description: "Up to 30 days for family death or imminent illness. American Red Cross verification. Funded leave travel for OCONUS Marines.",
    icon: "AlertCircle",
    pageType: "leaf",
  },
  {
    slug: "foreign-leave",
    label: "Foreign Leave",
    shortLabel: "Foreign Leave",
    description: "Travel to foreign countries on leave. Country clearance, ISOPREP, designated countries requiring approval, SOFA country requirements.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "terminal-leave",
    label: "Terminal Leave",
    shortLabel: "Terminal Leave",
    description: "End-of-service leave taken before separation. Sell-back option (60-day career cap). Cannot combine with parental leave.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "appellate-leave",
    label: "Appellate Leave",
    shortLabel: "Appellate Leave",
    description: "Leave awaiting punitive separation pending appellate review. Voluntary vs involuntary. NAMALA. Per MCO 1050.16A.",
    icon: "AlertCircle",
    pageType: "leaf",
  },
  {
    slug: "advance-and-excess-leave",
    label: "Advance and Excess Leave",
    shortLabel: "Advance/Excess",
    description: "Advance leave (borrow against future accrual). Excess leave (no pay, no allowances). Recoupment risk at separation.",
    icon: "CalendarDays",
    pageType: "leaf",
  },
  {
    slug: "leave-submission-and-administration",
    label: "Leave Submission and Administration",
    shortLabel: "Leave Admin",
    description: "MOL submission, MCTFS reconciliation, check-out and check-in, leave extensions, modifications, and cancellations.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "leave-problems-and-fixes",
    label: "Leave Problems and Fixes",
    shortLabel: "Leave Problems",
    description: "MOL-vs-MCTFS reconciliation, AOL, improper stacking, missing check-in, audit findings. The leave-side problem-fix flow.",
    icon: "AlertCircle",
    pageType: "leaf",
  },
  {
    slug: "rr-and-srr-leave-programs",
    label: "R&R and SR&R Leave Programs",
    shortLabel: "R&R / SR&R",
    description: "Combat zone R&R Leave (15 days mid-tour). SR&R Absence under OTEIP. Environmental and Morale Leave (EML).",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "birth-and-adoption",
    label: "Birth and Adoption",
    shortLabel: "Birth / Adoption",
    description: "Adding a child to DEERS via NAVMC 10922 and supporting documents. Birth certificate, adoption decree, paternity acknowledgment. 10 working day submission window. BAH-with-dependents implications. SGLI beneficiary updates. Per MCO 1751.3.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "child-custody-changes",
    label: "Child Custody Changes",
    shortLabel: "Child Custody",
    description: "Court-ordered custody add or loss. NAVMC 10922 with certified court order. BAH and Family Separation Allowance impact. DEERS enrollment or removal. Joint custody and BAH-Diff considerations. Per MCO 1751.3 and MCO 7220.24.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "death-of-dependent",
    label: "Death of Dependent",
    shortLabel: "Dependent Death",
    description: "Spouse, child, or secondary dependent death. NAVMC 10922 with certified death certificate. 10 working day submission. BAH adjustment, DEERS removal, ID card return, SGLI update, survivor benefits coordination. Per MCO 1751.3 and MCO 1770.1.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "deers-enrollment-and-id-cards",
    label: "DEERS Enrollment and ID Cards",
    shortLabel: "DEERS / ID Cards",
    description: "Defense Enrollment Eligibility Reporting System. RAPIDS sites. 30-day enrollment expectation. USIP card issuance and replacement. Eligibility windows, age outs, expiration. milConnect for online updates. Per DoDI 1000.13 and MCO 1751.3.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "dependency-validation-and-recertification",
    label: "Dependency Validation and Recertification",
    shortLabel: "Dependency Recert",
    description: "Annual dependency validation cycle. Recertification triggers (BAH, secondary dependency, student status). MARADMIN 661/19. Audit categories. Documentation refresh. Common loss of entitlement scenarios. Per MCO 1751.3.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "divorce-and-spouse-loss",
    label: "Divorce and Spouse Loss",
    shortLabel: "Divorce",
    description: "Final divorce decree submission. NAVMC 10922 within 10 working days. BAH adjustment effective day after divorce. DEERS removal of spouse. Child custody implications. SGLI beneficiary update. USFSPA considerations. Per MCO 1751.3 and 10 USC 1408.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "family-care-plan",
    label: "Family Care Plan (FCP)",
    shortLabel: "Family Care Plan",
    description: "Mandatory FCP for single parents, dual-military couples with dependents, and Marines with sole care responsibility. Short-term and long-term caregiver designations. NAVMC 11432 (Family Care Plan Certificate). 60-day completion window. Annual recertification. Per MCO 1740.13.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "life-events-overview",
    label: "Life Events Overview and Authorities",
    shortLabel: "Life Events Overview",
    description: "The framework. MCO 1751.3 (Marine Corps Dependency Determination and Support Program). NAVMC 10922 as the central document. 10 working day submission rule. DEERS, MCTFS, and OMPF integration. S-1 IPAC role. Audit weight. Common failure points.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "marriage-and-spouse-add",
    label: "Marriage and Spouse Add",
    shortLabel: "Marriage",
    description: "Adding a spouse to DEERS via NAVMC 10922 with certified marriage certificate. 10 working day submission. BAH-with-dependents start date. RAPIDS appointment for ID card. SGLI beneficiary update. TRICARE enrollment. Per MCO 1751.3.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "secondary-dependency-dd-137",
    label: "Secondary Dependency (DD Form 137)",
    shortLabel: "Secondary Dependency",
    description: "DD Form 137 Secondary Dependency Application. Seven dependency types (Incapacitated Adult Child, Student 21-22, Legal Custody Ward, Parent, Parent-in-Law, Stepparent, In-Loco Parentis). Over-half support test. Worksheet for Determining Financial Support. Per DoD 7000.14-R Volume 7A Chapter 26 and MCO 1751.3.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "pay-problems-and-fixes",
    label: "Pay Problems and Fixes",
    shortLabel: "Pay Problems",
    description: "Reading LES, BAH stopped, missing pays, debts, waivers.",
    icon: "AlertCircle",
    pageType: "leaf",
  },
  {
    slug: "pcs-orders-and-overview",
    label: "PCS Orders and Overview",
    shortLabel: "PCS Overview",
    description: "PCS authorities, orders types, service agreements, PCS types (accession, separation, retirement, COT, training).",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "dislocation-allowance",
    label: "Dislocation Allowance (DLA)",
    shortLabel: "DLA",
    description: "PCS allowance offsetting move costs. Rate by grade and dependent status. Per JTR Chapter 5.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "temporary-lodging-expense",
    label: "Temporary Lodging Expense (TLE)",
    shortLabel: "TLE",
    description: "CONUS PCS lodging allowance. Up to 14 days at the new or old PDS. With/without dependent rates.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "household-goods-and-ppm",
    label: "Household Goods (HHG) and PPM",
    shortLabel: "HHG/PPM",
    description: "HHG shipment, weight allowances by grade, PPM/DITY moves, temporary and non-temporary storage.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "pov-shipment-and-mileage",
    label: "POV Shipment and Mileage",
    shortLabel: "POV",
    description: "POV shipment OCONUS, MALT mileage CONUS, multiple POV authorization, POV storage.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "pcs-per-diem",
    label: "PCS Per Diem",
    shortLabel: "PCS Per Diem",
    description: "Per diem during PCS travel days. Member rate, dependent rate, MALT (Monetary Allowance In Lieu of Transportation).",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "member-and-dependent-travel",
    label: "Member and Dependent Travel",
    shortLabel: "Travel Modes",
    description: "Member transportation modes (air, POV, mixed). Dependent eligibility. Concurrent vs deferred travel.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "miscellaneous-expense-allowance",
    label: "Miscellaneous Expense Allowance (MEA)",
    shortLabel: "MEA",
    description: "MEA flat rate or itemized. Without-receipt and with-receipt frameworks. Per JTR.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "renewal-agreement-travel",
    label: "Renewal Agreement Travel (RAT) and COT",
    shortLabel: "RAT/COT",
    description: "RAT for OCONUS Marines extending overseas tour. Consecutive Overseas Tour (COT) framework.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "separation-retirement-accession-travel",
    label: "Separation, Retirement, and Accession Travel",
    shortLabel: "Sep/Ret/Accession",
    description: "PCS framework for separating, retiring, and new accession Marines. Home of selection, final move.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "pcs-with-tdy-en-route",
    label: "PCS with TDY En Route",
    shortLabel: "PCS/TDY",
    description: "PCS orders directing TDY en route (school, training). Per diem differences. Travel time computation.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "pet-transportation-allowance",
    label: "Pet Transportation Allowance",
    shortLabel: "Pet Transport",
    description: "Reimbursement for relocating one household pet (cat or dog) during PCS. $550 CONUS, $2,000 OCONUS. Per MARADMIN 573/24, effective 1 January 2024.",
    icon: "Truck",
    pageType: "leaf",
  },
  {
    slug: "human-breast-milk-shipment",
    label: "Human Breast Milk Shipment Reimbursement",
    shortLabel: "Breast Milk Shipment",
    description: "Up to $1,000 per PCS for active-duty nursing mothers within 12 months post-birth. Per MARADMIN 574/24. NOT for unaccompanied tours.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "childcare-provider-travel",
    label: "Childcare Provider Travel Pilot",
    shortLabel: "Childcare Travel",
    description: "Up to $500 CONUS or $1,500 OCONUS for designated childcare provider travel when CDC unavailable within 30 days of report. Pilot 2024-2027 per MARADMIN 573/24.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "flexible-spending-accounts",
    label: "Flexible Spending Accounts (DCFSA and HCFSA)",
    shortLabel: "FSA Accounts",
    description: "Pre-tax DCFSA up to $5,000 per household and HCFSA up to $3,200 per Marine. Enroll at FSAFEDS.gov. HCFSA opened to active-duty in 2025 per MARADMIN 573/24.",
    icon: "DollarSign",
    pageType: "leaf",
  },
  {
    slug: "promotions-overview",
    label: "Promotions Overview and Authorities",
    shortLabel: "Promotions Overview",
    description: "The framework. MCO P1400.32D (Enlisted), MCO 1400.31D (Officer). MMPB-10 and MMPB-11 organization. The 'best and fully qualified' philosophy. Records as the Marine's representation at boards.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "junior-enlisted-promotions",
    label: "Junior Enlisted Promotions (Pvt to Sgt)",
    shortLabel: "Junior Enlisted",
    description: "JEPES cutting scores, JEPA and JWKS in MCTFS, monthly promotion cycle, TIG/TIS minimum requirements, school honor graduate (5 percent rule), PME flag, junior remedial process per MARADMIN 559/23.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "non-competitive-cpl-to-sgt-promotions",
    label: "Non-Competitive Cpl-to-Sgt Promotions (SULI, Recruiter, IMOS)",
    shortLabel: "Non-Competitive to Sgt",
    description: "Four non-competitive paths for Cpl-to-Sgt promotion. SULI (MARADMIN 225/23). Active Duty Recruiter (MARADMIN 103/25). Reserve Component Recruiter (MARADMIN 229/25). Non-Competitive IMOS for 0211, 0372, 1751, 2336, 3044, 4133, 4821, 5821 (MARADMIN 515/25 effective 1 October 2025).",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "snco-selection-boards",
    label: "SNCO Selection Boards (SSgt and Above)",
    shortLabel: "SNCO Boards",
    description: "Pre-board, board, post-board phases. Board composition (Colonel president, 20 voting members). Discrepancy Notices. IMOS/OCCFLD voting. Above zone, in zone, below zone (10 percent or 2 selections from below zone). Annual schedule.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "officer-promotion-boards",
    label: "Officer Promotion Boards",
    shortLabel: "Officer Boards",
    description: "MMPB-10 framework. Statutory selection boards. Convening messages. My Eligibility tool. Boards & Surveys portal upload. Officer correspondence to board president (10-day deadline). Reservist RQS. Warrant reprints.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "selection-board-preparation",
    label: "Selection Board Preparation (Records and Materials)",
    shortLabel: "Board Preparation",
    description: "OMPF (S/C/P folders), MBS framework, O-RMA access, 90-day pre-board audit. Sending material to board president (signed cover letter, 10-day deadline). Photos no longer required for SNCO boards. Material destroyed after the board.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "meritorious-promotions",
    label: "Meritorious Promotions",
    shortLabel: "Meritorious",
    description: "Combat Meritorious. Non-combat Meritorious. MCCAP. SDA. Drill Instructor and Recruiter of the Year. Allocation MARADMIN schedule. CMC delegation framework. Meritorious limited to MSgt (1stSgt not authorized).",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "pme-requirements-for-promotion",
    label: "PME Requirements for Promotion",
    shortLabel: "PME for Promotion",
    description: "Sequenced PME provisions. MarineNet EPME. Resident schools. Seminar Program. SDA billet waiver (specific MOSs). MARADMINs 630/24 and 631/24. PME revocation timelines for SSgt/GySgt selects.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "obligated-service-for-promotion",
    label: "Obligated Service (OBS) and Reenlistment for Promotion",
    shortLabel: "OBS for Promotion",
    description: "24-month OBS for SNCO selectees. CO extension authority (with DCC AF/AH/AX/AY limitations). Direct Affiliation Program (DAP). Refusal consequences (removal from list, ineligible for future PSBs in same component). Medical exemptions.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "promotion-delays-and-revocations",
    label: "Promotion Delays and Revocations",
    shortLabel: "Delays / Revocations",
    description: "SNCO Undelivered Appointments. CO advance notification, then 30-day full report. Marine's right to review and statement. Endorsement chain process per paragraph 5200.5.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "remedial-selection",
    label: "Remedial Selection (ERSB and Junior Enlisted)",
    shortLabel: "Remedial Selection",
    description: "ERSB framework per MCO 5420.16D. Reasons for approval (erroneous omission, PERB removal, etc.). Reasons for disapproval. Submission process. Junior enlisted auto-remedial through MCTFS recompute per MARADMIN 559/23.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "failure-of-selection",
    label: "Failure of Selection and Non-Selection",
    shortLabel: "Failure of Selection",
    description: "What non-selection means. Twice-passed policy. Alternate selection list. Requesting non-selection (10-day deadline). Post-board career counseling through MMEA-64. Why MMPB-11 cannot disclose specific non-selection reasons.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "reenlistments-and-extensions-overview",
    label: "Reenlistments and Extensions Overview and Authorities",
    shortLabel: "Reenlistments Overview",
    description: "The framework. MCO 1040.31 (Enlisted Retention and Career Development Program). Career Counselor as central figure. Total Force Retention System (TFRS). MARADMIN ecosystem (annual retention campaign, SRB, force shaping). Stay Marine philosophy. Common failure points.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "reenlistment-eligibility-and-process",
    label: "Reenlistment Eligibility and Process",
    shortLabel: "Reenlistment Eligibility",
    description: "The 4-step process (Career Counselor consultation, package completion, return to Career Counselor, action upon HQMC decision). NAVMC 11537 (RELM). Package components. Eligibility criteria.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "first-term-reenlistments-ftap",
    label: "First-Term Reenlistments (FTAP)",
    shortLabel: "FTAP",
    description: "First-Term Alignment Plan. Commandant's Retention Program (CRP) with 20% per MOS and Enhanced DSI (EDSI). Commanding General's Retention Program (CGRP) for boatspace caps reached. FY26 and FY27 timelines per MARADMIN 590/25.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "career-reenlistments-stap",
    label: "Career Reenlistments (STAP)",
    shortLabel: "STAP",
    description: "Subsequent Term Alignment Plan. Senior Enlisted Alignment Plan (SEAP). Enlisted Career Designation Program (ECDP) Pilot per MARADMIN 076/25 for E-8/E-9. Streamlined processing for E-6 through E-8 board selectees. Geolocation preferences.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "boatspaces-and-allocations",
    label: "Boatspaces and Allocations",
    shortLabel: "Boatspaces",
    description: "Core control mechanism. MOS-specific quotas. Rank-specific allocations. Managed by HQMC. Released via MARADMIN. Drives retention competition and PMOS-specific availability.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "selective-retention-bonus-and-targeted-mos",
    label: "Selective Retention Bonus (SRB) and Targeted MOS Bonuses",
    shortLabel: "SRB / Targeted MOS",
    description: "Annual SRB MARADMIN. Zones A through F. Lump sum vs installment. Bonus-eligible MOS list. Kicker programs (Aircraft Maintenance, Aircraft Readiness, 84-month LM, 72-month Mid-Career LM, 24/36-month FMF Infantry, Air Traffic Controller). $360,000 career SRB cap. Per MCO 7220.24P and MARADMIN 023/26 (FY27).",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "duty-station-incentive",
    label: "Duty Station Incentive (DSI)",
    shortLabel: "DSI",
    description: "First-Term Marines on-station 18+ months requesting 36+ months reenlistment may submit up to 3 DSI preferences. Common DSI choices (Pendleton, Lejeune, Hawaii, Okinawa, etc.). Enhanced DSI (EDSI) for CRP selectees.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "slip-duty-station-incentive",
    label: "Strategic Location Incentive Program (SLIP)",
    shortLabel: "SLIP",
    description: "Volunteer for a hard-to-fill duty station overseas or in remote locations, earn the right to choose your follow-on duty station. MARADMIN 470/24. MOS-specific eligible locations. Eligibility: Zones B/C/D reenlistment, valid RE code, not HSST-screened, time-on-station requirement met.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "slip-eligible-billets-by-mos",
    label: "SLIP Eligible Billets by MOS",
    shortLabel: "SLIP Billets",
    description: "Quick reference table of SLIP-eligible duty stations by military occupational specialty. Representative locations only. Your PMOS monitor determines current availability and what counts as difficult to fill.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "lateral-moves-program",
    label: "Lateral Moves (LATMOVE) Program",
    shortLabel: "LATMOVE",
    description: "LATMOVE framework. Voluntary vs Directed (force shaping). FY26 LATMOV opportunities per MARADMIN 365/25 covering 12 MOSs (FTAP and STAP). FY27 framework per MARADMIN 590/25. ASVAB requirements. School seat availability.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "extensions",
    label: "Extensions",
    shortLabel: "Extensions",
    description: "Short-term retention tool. Three types (Convenience of Government, Personal Convenience, Operational). Local Command Authority (LCA) extensions. Maximum cumulative limits. NOT a substitute for reenlistment. Per MCO 1040.31.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "direct-affiliation-program",
    label: "Direct Affiliation Program (DAP)",
    shortLabel: "DAP",
    description: "Active-to-Reserve transition. Year-round submission. NET 365 days prior to EAS. NLT 30 days from EAS. Affiliate with SMCR, IMA, AR, or IRR. Retains promotion selection. Per MCO 1040.31 and MARADMIN 590/25.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "separations-and-retirement-overview",
    label: "Separations and Retirement Overview and Authorities",
    shortLabel: "Sep/Ret Overview",
    description: "The framework. MCO 1900.16 (MARCORSEPMAN). MMSR organizational structure (MMSR-2 enlisted, MMSR-4 disability/limdu, MMSR-5 reserve, MMSR-6 retired services). Lifecycle perspective. Common failure points.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "voluntary-separations",
    label: "Voluntary Separations",
    shortLabel: "Voluntary Sep",
    description: "End of Active Service (EAS), Early Release Programs, Convenience of the Government, Dependency or hardship, Education programs. Per MCO 1900.16.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "involuntary-separations",
    label: "Involuntary Separations",
    shortLabel: "Involuntary Sep",
    description: "Misconduct (minor, pattern, serious), Unsatisfactory performance, Failure to meet standards (body composition, PFT), Drug abuse. Per MCO 1900.16. Cross-reference Administrative Separation in Legal Services.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "spd-and-re-codes",
    label: "SPD and RE Codes",
    shortLabel: "SPD / RE Codes",
    description: "Separation Program Designator (SPD) codes. Reenlistment Eligibility codes (RE-1 through RE-4). DD214 narrative reason. Impact on future service.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "separation-pay-and-final-pay",
    label: "Separation Pay and Final Pay",
    shortLabel: "Separation Pay",
    description: "Final pay calculation. Leave sell-back. Separation pay (Full and Half Involuntary Separation Pay). Travel entitlements. Cross-reference Separation Payments in Pay and Entitlements.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "transition-requirements",
    label: "Transition Requirements",
    shortLabel: "Transition Reqs",
    description: "Transition Readiness Seminar (TRS), Capstone, Individual Transition Plan (ITP). VA benefits at separation. GI Bill at separation. SkillBridge integration. Per DoD and Marine Corps transition policy.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "retirement-types-and-eligibility",
    label: "Retirement Types and Eligibility",
    shortLabel: "Retirement Types",
    description: "Length of service (20+ years active). Temporary Early Retirement Authority (TERA, 15-19 years when authorized). Reserve retirement (cross-reference). Disability retirement (cross-reference).",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "retirement-timeline",
    label: "Retirement Timeline (36 Months Through Post-Retirement)",
    shortLabel: "Retirement Timeline",
    description: "Seven-phase framework. 36-24 months (Earliest), 24-18 (Long-Range Planning), 18-12 (Plan and Preparation), 12-6 (Finalization), 6-1 (Execution), Month of Retirement, 0-12 Post-Retirement.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "retired-pay-and-sbp",
    label: "Retired Pay and Survivor Benefit Plan (SBP)",
    shortLabel: "Retired Pay / SBP",
    description: "High-3 retirement system. Blended Retirement System (BRS). Years of service multiplier. SBP elections (active duty). COLA. Tax considerations. Cross-reference RCSBP for Reserve.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "limited-duty",
    label: "Limited Duty (TLD, PLD, EPLD)",
    shortLabel: "Limited Duty",
    description: "Light duty (90 days). Temporary Limited Duty (TLD/LIMDU, Form 6100-5, Q duty limit code). Permanent Limited Duty (PLD). Expanded PLD (EPLD per MARADMIN 457/16). Medical extensions (NAVMC 321M).",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "disability-evaluation-system",
    label: "Disability Evaluation System (DES) Process and Outcomes",
    shortLabel: "DES",
    description: "Three phases (MEB, IPEB, FPEB). Two pathways (LDES and IDES) plus IODES for OCONUS. PEBLO. Six outcomes (Fit, Presumed Fit, Unfit with severance, Unfit without severance, TDRL, PDRL). Per MCO 1900.16 Ch 2.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "reserve-retirement",
    label: "Reserve Retirement (Qualifying Years, Points, Reduced Age)",
    shortLabel: "Reserve Retirement",
    description: "Reserve retirement framework. Qualifying service per 10 USC 12732. Retirement points (active, inactive, membership). Anniversary year. 50-point and 27-point participation. Pro-rating. Age 60 pay start with NDAA 2008/2011 reductions. DD Form 214-1.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "reserve-component-survivor-benefit-plan",
    label: "Reserve Component Survivor Benefit Plan (RCSBP)",
    shortLabel: "RCSBP",
    description: "20-Year Letter (Notice of Eligibility). 90-day election window. Three options (A. Decline, B. Deferred, C. Immediate). Beneficiary types. Premiums (SBP plus RCSBP add-on). Active Reserve framework. 12-month life event window.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "officer-bonuses",
    label: "Officer Bonuses",
    shortLabel: "Officer Bonuses",
    description: "Accession, RC affiliation, retention, transfer bonuses, command pay. $300K career cap.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "enlisted-bonuses",
    label: "Enlisted Bonuses",
    shortLabel: "Enlisted Bonuses",
    description: "EB up to $75K, SRB up to $30K/year, CSRB, prior service, conversion, transfer bonuses.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "special-duty-assignment-pay",
    label: "Special Duty Assignment Pay (SDAP)",
    shortLabel: "SDAP",
    description: "Recruiters, Drill Instructors, MSG Detachment Commanders. $150/month flat rate per MARADMIN 628/20.",
    icon: "Briefcase",
    pageType: "leaf",
  },
  {
    slug: "volunteer-supplemental-incentive",
    label: "Volunteer Supplemental Incentive (VSI)",
    shortLabel: "VSI",
    description: "$10,000 lump sum or $278/month for 36-month SDA tour. Volunteers only. Combat Instructors not eligible.",
    icon: "Star",
    pageType: "leaf",
  },
  {
    slug: "hazardous-duty-incentive-pay",
    label: "Hazardous Duty Incentive Pay (HDIP)",
    shortLabel: "HDIP",
    description: "Parachute (jump), demolition, flight deck, toxic fuel, chemical munitions duty.",
    icon: "AlertCircle",
    pageType: "leaf",
  },
  {
    slug: "diving-duty-pay",
    label: "Diving Duty Pay",
    shortLabel: "Diving Pay",
    description: "Designated divers in Recon, Force Recon, EOD, combat engineers. Up to $240/month.",
    icon: "LifeBuoy",
    pageType: "leaf",
  },
  {
    slug: "career-sea-pay",
    label: "Career Sea Pay (CSP)",
    shortLabel: "Sea Pay",
    description: "CSP and CSP-Premium for Marines on sea duty. CSP-P after 36 consecutive months.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "hardship-duty-pay",
    label: "Hardship Duty Pay (HDP)",
    shortLabel: "Hardship Pay",
    description: "HDP-Location, HDP-Mission, HDP-Tempo, HDP-ROM. Substandard living conditions or arduous duty.",
    icon: "AlertCircle",
    pageType: "leaf",
  },
  {
    slug: "foreign-language-proficiency-bonus",
    label: "Foreign Language Proficiency Bonus (FLPB)",
    shortLabel: "FLPB",
    description: "Up to $1,000/month or $12,000/year for certified critical-language proficiency.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "aviation-incentive-pays",
    label: "Aviation Incentive Pays",
    shortLabel: "Aviation Incentive",
    description: "Flying-duty HDIP, AvIP for officers, CSIP for enlisted aviation skills.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "aviation-bonus",
    label: "Aviation Bonus (AvB)",
    shortLabel: "Aviation Bonus",
    description: "Up to $35K/year for RC pilots and UAS operators in critical aviation specialties.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "continuation-pay",
    label: "Continuation Pay (CP)",
    shortLabel: "Continuation Pay",
    description: "BRS-only mid-career bonus at 8-12 YOS. 2.5x to 13x monthly basic pay.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "high-deployment-allowance",
    label: "High-Deployment Allowance (HDA)",
    shortLabel: "HDA",
    description: "Up to $1,000/month after 191 consecutive deployed days or 401/730-day pattern.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "assignment-incentive-pay",
    label: "Assignment Incentive Pay (AIP)",
    shortLabel: "AIP",
    description: "Combat Instructors, MSG Watch Standers, Career Planners, MARSOC, SgtMajs, Career Recruiters. Monthly or lump sum (NAVMC 118-11).",
    icon: "Briefcase",
    pageType: "leaf",
  },
  {
    slug: "oconus-tour-extension-incentive",
    label: "OCONUS Tour Extension Incentive",
    shortLabel: "OCONUS Extension",
    description: "Up to $80/month or $2,000/year (or 30 days SR&R absence) for extending OCONUS tours.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "health-professions-officer-pays",
    label: "Health Professions Officer Special Pays",
    shortLabel: "HPO Pays",
    description: "Medical, dental, nurse corps special pays. Limited Marine Corps applicability (Navy medical).",
    icon: "Heart",
    pageType: "leaf",
  },
  {
    slug: "conus-cola",
    label: "CONUS Cost of Living Allowance",
    shortLabel: "CONUS COLA",
    description: "Recurring monthly allowance for designated high-cost CONUS areas. Taxable.",
    icon: "Home",
    pageType: "leaf",
  },
  {
    slug: "oconus-cola",
    label: "OCONUS Cost of Living Allowance",
    shortLabel: "OCONUS COLA",
    description: "Non-taxable allowance offsetting OCONUS prices of goods and services excluding housing.",
    icon: "Home",
    pageType: "leaf",
  },
  {
    slug: "clothing-monetary-allowances",
    label: "Clothing Monetary Allowances",
    shortLabel: "Clothing Allowance",
    description: "Initial clothing allowance, Basic CCRA, Standard CCRA, supplementary and civilian clothing allowances.",
    icon: "Shirt",
    pageType: "leaf",
  },
  {
    slug: "sgli-and-vgli",
    label: "SGLI, FSGLI, TSGLI, and VGLI",
    shortLabel: "SGLI",
    description: "Servicemembers Group Life Insurance. $500K default, FSGLI for spouses, TSGLI traumatic injury, VGLI at separation.",
    icon: "Heart",
    pageType: "leaf",
  },
  {
    slug: "federal-tax-withholding",
    label: "Federal and State Tax Withholding",
    shortLabel: "Tax Withholding",
    description: "FITW and SITW on taxable pay. BAH/BAS non-taxable. CZTE for combat zone service. W-4 updates through MyPay.",
    icon: "FileText",
    pageType: "leaf",
  },
  {
    slug: "tsp-and-savings",
    label: "Thrift Savings Plan (TSP) and BRS Matching",
    shortLabel: "TSP",
    description: "BRS auto-enroll at 5%, agency 1% automatic, 4% match cap. Roth vs Traditional. 25-month vesting on agency 1%.",
    icon: "TrendingUp",
    pageType: "leaf",
  },
  {
    slug: "allotments",
    label: "Allotments (Discretionary, Nondiscretionary, Garnishments)",
    shortLabel: "Allotments",
    description: "Up to 6 discretionary allotments. Personal property purchases prohibited since 2015. Garnishments for child support.",
    icon: "DollarSign",
    pageType: "leaf",
  },
  {
    slug: "separation-payments",
    label: "Separation Payments (Severance, VSP, Disability)",
    shortLabel: "Separation Pay",
    description: "Full and Half Separation Pay (10% formula), Disability Severance Pay, VSP, accrued leave (60-day cap), recoupment.",
    icon: "LogOut",
    pageType: "leaf",
  },
  {
    slug: "reserve-pay-and-entitlements",
    label: "Reserve Pay and Entitlements",
    shortLabel: "Reserve Pay",
    description: "Drill pay (1/30 per IDT period, 4/weekend), AT pay, mobilization pay, MDA for IRR, RIRP for income replacement.",
    icon: "RefreshCcw",
    pageType: "leaf",
  },
  {
    slug: "advance-and-emergency-pay",
    label: "Advance, Local, Partial, and Emergency Pay",
    shortLabel: "Advance Pay",
    description: "PCS advance up to 3 months basic pay. Advance BAH and DLA. Local pay for missed paychecks. Emergency partial pay.",
    icon: "AlertCircle",
    pageType: "leaf",
  },
  {
    slug: "illness-or-injury-payments",
    label: "Illness or Injury Pay Continuation",
    shortLabel: "PAC and SCAADL",
    description: "PAC preserves combat-zone pays during recovery up to 12 months. SCAADL stipend for catastrophic injury caregivers.",
    icon: "Heart",
    pageType: "leaf",
  },
  {
    slug: "death-payments",
    label: "Death Payments and Survivor Benefits",
    shortLabel: "Death Payments",
    description: "$100K Death Gratuity, SGLI payout up to $500K, arrears of pay, 365-day BAH continuation, DIC, SBP, CACO coordination.",
    icon: "Heart2",
    pageType: "leaf",
  },
  {
    slug: "court-martial-and-njp-pay-impact",
    label: "Court-Martial and NJP Pay Impact",
    shortLabel: "CM/NJP Pay",
    description: "Forfeitures (partial and total), reduction in grade, 14-day effective date, suspended punishment, pay restoration.",
    icon: "AlertCircle",
    pageType: "leaf",
  },
  {
    slug: "fica-and-afrh-deductions",
    label: "FICA and AFRH Deductions",
    shortLabel: "FICA/AFRH",
    description: "Social Security 6.2%, Medicare 1.45%, Additional Medicare Tax 0.9% above threshold. AFRH $0.50/month for enlisted/warrant/LDO.",
    icon: "DollarSign",
    pageType: "leaf",
  },
  {
    slug: "officers-uniform-and-equipment-allowance",
    label: "Officers Uniform and Equipment Allowance",
    shortLabel: "Officer Uniform",
    description: "$400 Initial Uniform Allowance one-time at commissioning. $200 Additional Active-Duty for RC officers re-entering AD over 90 days.",
    icon: "Shirt",
    pageType: "leaf",
  },
  {
    slug: "bankruptcy-and-pay",
    label: "Bankruptcy and Pay",
    shortLabel: "Bankruptcy",
    description: "Chapter 7 vs Chapter 13. Automatic stay halts pre-petition debt. Child support continues. DFAS Garnishment Law Directorate.",
    icon: "AlertCircle",
    pageType: "leaf",
  },
  {
    slug: "comparable-grades",
    label: "Comparable Grades (Cross-Service Rank Reference)",
    shortLabel: "Comparable Grades",
    description: "Cross-service pay grade reference. O-1 to O-10, W-1 to W-5, E-1 to E-9 across all six services.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "priority-of-pay-deductions",
    label: "Priority of Pay Deductions and Collections",
    shortLabel: "Priority of Deductions",
    description: "17-level priority order for deductions when pay is insufficient. Forfeitures first, then statutory, then debts, then voluntary.",
    icon: "ClipboardList",
    pageType: "leaf",
  },
  {
    slug: "tdy-tad-overview",
    label: "TDY/TAD Overview and Orders",
    shortLabel: "TDY Overview",
    description: "TDY/TAD authorization framework, orders types, funding sources, AO and RO oversight.",
    icon: "Briefcase",
    pageType: "leaf",
  },
  {
    slug: "tdy-per-diem",
    label: "TDY Per Diem",
    shortLabel: "TDY Per Diem",
    description: "M&IE rates, lodging rates, reduced per diem, flat-rate per diem (30+/180+ days), proportional meal rate.",
    icon: "Briefcase",
    pageType: "leaf",
  },
  {
    slug: "tdy-lodging",
    label: "TDY Lodging",
    shortLabel: "TDY Lodging",
    description: "Government quarters availability, Integrated Lodging Program (ILP), commercial lodging limits, AEA framework.",
    icon: "Briefcase",
    pageType: "leaf",
  },
  {
    slug: "tdy-transportation",
    label: "TDY Transportation",
    shortLabel: "TDY Transport",
    description: "Air travel (city pair, GSA fares), rental car authorization, POV use on TDY, local transportation.",
    icon: "Briefcase",
    pageType: "leaf",
  },
  {
    slug: "creating-dts-authorizations",
    label: "Creating DTS Authorizations",
    shortLabel: "DTS Authorizations",
    description: "Pre-travel DTS workflow. Building the authorization, City Pair air, hotel and rental car bookings, Lines of Accounting, AO routing and approval. Per JTR Chapter 4 and MCO 4650.39A.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "dts-outstanding-travel-orders",
    label: "DTS Outstanding Travel Orders (OTOs) and Zero-Dollar Vouchers",
    shortLabel: "OTOs and Zero Vouchers",
    description: "OTO management per MARADMIN 359/25. Automated 90-day zero-dollar voucher processing by DTS PMO. NDEA submission framework. CBA reconciliation at 45 days. Exemption categories.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "dts-overview",
    label: "DTS Overview and Authorities",
    shortLabel: "DTS Overview",
    description: "DTS program framework. Authorities (MCO 4650.39A, DODFMR Vol 9, JTR), governance, RFF DTS PMO, CTOs, system integration with MyPay and Citi.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "dts-profile-and-setup",
    label: "DTS Profile and Setup",
    shortLabel: "DTS Profile",
    description: "Setting up your DTS profile. GTCC integration, EFT bank account for split disbursement, AO routing list, organizational placement, profile updates after PCS.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "dts-roles-and-routing",
    label: "DTS Roles and Routing",
    shortLabel: "DTS Roles",
    description: "Traveler, ODTA, LDTA, FDTA, NDEA, AO at unit, AO at Disbursing Office, Reviewing Official, DTS PMO, Debt Management Monitor. The Zero Voucher routing list. Per MCO 4650.39A and MARADMIN 291/12.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "dts-voucher-approval-process",
    label: "DTS Voucher Approval Process",
    shortLabel: "DTS Approval",
    description: "Per MARADMIN 291/12. DO/FO routing for final approval, blanket grade waiver for AO/COs, 2-day Reviewing Official window, 3-day Approving Official window, TECOM Worldwide Travel exception.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "idt-travel-reimbursement",
    label: "IDT Travel Reimbursement",
    shortLabel: "IDT Travel",
    description: "Per MARADMIN 157/25. $750 cap effective 27 December 2024 (was $500). 150-mile distance test from PRA. BIC match. 11 round trips per FY (22 for aviators). MARFORRES manages LOA via DTS.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "submitting-dts-vouchers",
    label: "Submitting DTS Vouchers",
    shortLabel: "DTS Vouchers",
    description: "Post-travel DTS voucher submission. 5-working-day rule, receipt requirements, split disbursement, CBA reconciliation, supplemental vouchers. Per JTR Chapter 4 and DTMO Voucher Guide.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "dts-trip-cancellations",
    label: "Trip Cancellations in DTS",
    shortLabel: "Trip Cancellations",
    description: "Cancel-with-expenses vs cancel-without-expenses. Mandatory expenses (lodging cancellation fees, TMC booking fees, CBA charges). When NOT to cancel an authorization. Per MARADMIN 359/25 and DTMO Authorizations Guide.",
    icon: "Plane",
    pageType: "leaf",
  },
  {
    slug: "gtcc-overview",
    label: "GTCC Overview and Authorities",
    shortLabel: "GTCC Overview",
    description: "DoD GTCC program framework, IBA vs CBA, statutory and regulatory authorities. Per DoDI 5154.31 Vol 4, MCO 4600.40C, and MARADMIN 478/24.",
    icon: "CreditCard",
    pageType: "leaf",
  },
  {
    slug: "apply-for-gtcc",
    label: "Apply for a GTCC",
    shortLabel: "Apply for GTCC",
    description: "Application workflow. SOU, Travel Card 101 in TraX, DD Form 2883 alternate credit evaluation, expedited delivery, September 2025 form update with January 2026 deadline.",
    icon: "CreditCard",
    pageType: "leaf",
  },
  {
    slug: "standard-vs-restricted-iba",
    label: "Standard vs Restricted IBAs",
    shortLabel: "Standard vs Restricted",
    description: "FICO 660 cutoff. Standard credit and cash limits. Restricted credit and cash limits. Mission-critical limit raises validated by commanders.",
    icon: "CreditCard",
    pageType: "leaf",
  },
  {
    slug: "gtcc-account-management",
    label: "Manage Your GTCC Account",
    shortLabel: "GTCC Account Mgmt",
    description: "CitiManager portal, mobile app, statements, payments, paperless enrollment, alerts, mailing payment addresses, Citi 24/7 customer service.",
    icon: "CreditCard",
    pageType: "leaf",
  },
  {
    slug: "gtcc-split-disbursement",
    label: "GTCC Split Disbursement",
    shortLabel: "Split Disbursement",
    description: "Mandatory DoD-wide. Pay GTCC bill directly from travel reimbursement. DTS configuration. Verify amounts before voucher submission.",
    icon: "CreditCard",
    pageType: "leaf",
  },
  {
    slug: "gtcc-pcs-use",
    label: "GTCC Use During PCS (MARADMIN 478/24)",
    shortLabel: "GTCC for PCS",
    description: "ELT OCONUS Marine GTCC issuance per MARADMIN 478/24. Losing and gaining APC roles. PCS/Mission Critical status codes. Hierarchy transfers. Prohibited use during PTAD or leave.",
    icon: "CreditCard",
    pageType: "leaf",
  },
  {
    slug: "gtcc-tdy-use",
    label: "GTCC Use During TDY",
    shortLabel: "GTCC for TDY",
    description: "Authorized TDY uses (transportation, lodging, rental car, meals). Prohibited uses (personal, non-TDY). DTS integration. CBA for travelers without IBA.",
    icon: "CreditCard",
    pageType: "leaf",
  },
  {
    slug: "gtcc-misuse-and-suspension",
    label: "GTCC Misuse, Suspension, and Cancellation",
    shortLabel: "GTCC Misuse",
    description: "Personal use prohibitions. UCMJ implications. Page 11 entries. Suspension thresholds (60-day delinquency). Cancellation framework. Reinstatement after suspension.",
    icon: "CreditCard",
    pageType: "leaf",
  },
  {
    slug: "long-term-tdy",
    label: "Long-Term TDY",
    shortLabel: "Long-Term TDY",
    description: "TDY over 30 days. Reduced per diem at 30+ days. Flat-rate per diem at 180+ days. ITRA for extended TDY.",
    icon: "Briefcase",
    pageType: "leaf",
  },
  {
    slug: "travel-vouchers-and-reimbursement",
    label: "Travel Vouchers and Reimbursement",
    shortLabel: "Vouchers",
    description: "Voucher submission, receipts requirements, miscellaneous reimbursable expenses, common errors.",
    icon: "Briefcase",
    pageType: "leaf",
  },
  {
    slug: "civilian-degree-pursuit",
    label: "Civilian Degree Pursuit",
    shortLabel: "Civilian Degree",
    description: "Pursuing associate, bachelor, or graduate degrees while on active duty. Accreditation requirements. Coordination with VolEd and TA. Off-duty schedule considerations.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "dantes-testing",
    label: "DANTES Testing (CLEP, DSST, AP)",
    shortLabel: "DANTES Testing",
    description: "College Level Examination Program (CLEP). DSST testing. Advanced Placement. Earn college credit through testing. Free for active-duty Marines. Per DANTES policy.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "education-overview",
    label: "Education Overview and Authorities",
    shortLabel: "Education Overview",
    description: "The framework. MCO 1560.25 Marine Corps Voluntary Education Program. Education Centers at MCCS. Coordination across TA, GI Bill, MarineNet, and civilian education. Common failure points.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "education-at-transition",
    label: "Education at Transition",
    shortLabel: "Transition Education",
    description: "Education planning for separating and retiring Marines. GI Bill activation timing. VR&E (Chapter 31) eligibility. Education during SkillBridge. Cross-reference to Transition Readiness Program.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "joint-professional-military-education",
    label: "Joint Professional Military Education (JPME)",
    shortLabel: "JPME",
    description: "JPME Phase I and II. War College. Resident and non-resident options. Joint Qualified Officer (JQO) designation. Per CJCS Instruction 1800.01.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "marine-corps-university",
    label: "Marine Corps University and Resident Schools",
    shortLabel: "MCU / Schools",
    description: "Marine Corps University. Expeditionary Warfare School (EWS). Command and Staff College (CSC). Marine Corps War College (MCWAR). SNCO Academy. Resident, blended, and distance learning.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "marinenet-and-distance-learning",
    label: "MarineNet and Distance Learning",
    shortLabel: "MarineNet",
    description: "MarineNet at marinenet.usmc.mil. Online courses and required training. PME completion. Course catalog. ACE-recommended college credit.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "montgomery-gi-bill",
    label: "Montgomery GI Bill (MGIB-AD and MGIB-SR)",
    shortLabel: "MGIB",
    description: "Montgomery GI Bill Active Duty (MGIB-AD, Chapter 30) and Selected Reserve (MGIB-SR, Chapter 1606). Eligibility, election, monthly payments. Per 38 USC Chapter 30 and 10 USC Chapter 1606.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "post-9-11-gi-bill",
    label: "Post-9/11 GI Bill",
    shortLabel: "Post-9/11 GI Bill",
    description: "Post-9/11 GI Bill (Chapter 33) eligibility, percentage tiers, tuition payment, housing allowance, books stipend. Transfer of Education Benefits (TEB) to dependents. Per 38 USC Chapter 33.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "tuition-assistance",
    label: "Tuition Assistance (TA)",
    shortLabel: "TA",
    description: "Tuition Assistance for off-duty courses. $4,500 per fiscal year. $250 per semester hour. Eligibility, application, completion requirements. Coordination with GI Bill. Per MCO 1560.25.",
    icon: "GraduationCap",
    pageType: "leaf",
  },
  {
    slug: "career-services",
    label: "MF Career Services",
    shortLabel: "Career Services",
    description: "Family Member Employment Assistance Program (FMEAP). SkillBridge (cross-reference). Credentialing Opportunities OnLine (COOL). United Services Military Apprenticeship Program (USMAP). Transition Readiness Program (TRP, cross-reference). Volunteer Program. Per MCO 1700.30 and Marine Corps Community Services policy.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "casualty-assistance-program",
    label: "Casualty Assistance Program (CAP and CACO)",
    shortLabel: "CAP / CACO",
    description: "HQMC Casualty Section. Personnel Casualty Report (PCR). Casualty Assistance Calls Officer (CACO) assignment for deceased, DUSTWUN, and missing Marines. In-person notification with chaplain accompaniment. Invitational Travel Orders (ITO) for bedside travel. 800-847-1597 24/7 hotline. Per MCO 3040.4 and MCO 1770.1.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "casualty-investigation-tracking",
    label: "Casualty Investigation Tracking",
    shortLabel: "Investigations",
    description: "Line of Duty Determinations (LODD) per JAGMAN Part E Section 0212. Command investigations for General Court Martial Convening Authority. Coordination with NCIS, CID, and Naval Safety Center. Information delivery to next of kin via CACO. Per JAGMAN and MCO 1770.1.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "child-and-youth-programs",
    label: "Child and Youth Programs (CYP)",
    shortLabel: "CYP",
    description: "Child Development Programs for ages 6 weeks through 12 years. Child Development Centers, School Age Care, Family Child Care homes. Youth Programs for ages 6 to 18. Full-day, part-time, and hourly child care. MCCS Child Care request system. Per Marine Corps Community Services policy.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "education-services-and-resilience",
    label: "MF Education Services and Resilience",
    shortLabel: "Education / Resilience",
    description: "Leadership Scholar Program (LSP). Voluntary Education Program (VolEd). Library Program. Chaplain Religious Enrichment Development Operation (CREDO). Marine for Life Network. Installation-based programs supporting literacy, academic efforts, and personal/family resilience.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "exceptional-family-member-program",
    label: "Exceptional Family Member Program (EFMP)",
    shortLabel: "EFMP",
    description: "Support for military families with special medical or educational needs. DD Form 2792 (Family Member Medical Summary) and DD Form 2792-1 (Special Education/Early Intervention Summary). PCS continuity of care. TRICARE coordination. Career progression and promotion impact. HQMC EFMP at hqmc.efmp@usmc.mil.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "family-readiness-services",
    label: "Family Readiness Services (UPFRP)",
    shortLabel: "Family Readiness",
    description: "Unit, Personal and Family Readiness Program (UPFRP) umbrella. Marine Corps Family Team Building (MCFTB). Information, Referral and Relocation Program (IR&R). Sponsorship Program. Family Readiness Officer (FRO). Per MCO 1754.9.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "marine-and-family-programs-overview",
    label: "Marine and Family Programs Overview and Authorities",
    shortLabel: "MF Overview",
    description: "Marine and Family Programs Branch (MF) at HQMC. Marine Corps Community Services (MCCS) at installations. Program scope (casualty, family, career, education, financial, resilience). How to find programs. Coordination with HQ UPFRP, EFMP, Casualty Section, and other MF subdivisions.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "military-funeral-honors-and-repatriation",
    label: "Military Funeral Honors and Repatriation",
    shortLabel: "Funeral Honors",
    description: "Military Funeral Honors ceremony. Folding and presentation of American flag. Sounding of Taps by detail of two uniformed members minimum, plus bugler when available. Marine Corps detail standard. Repatriation Program for Marines unaccounted for from previous conflicts. DPAA, AFDIL, LSEL coordination. 866-210-3421 Option 1.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "personal-financial-management-program",
    label: "Personal Financial Management Program (PFMP)",
    shortLabel: "PFMP",
    description: "Installation-based financial counseling. Debt management. Budgeting and savings. Major life event financial planning (marriage, baby, divorce, PCS, deployment, retirement). Coordination with Navy-Marine Corps Relief Society for emergency financial assistance. Per MCO 1740.13 and Marine Corps Community Services policy.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "school-liaison-program",
    label: "School Liaison Program (SLP)",
    shortLabel: "SLP",
    description: "Coordinates community resources to reduce impact of mobile military lifestyle on military school-aged children. PCS school transitions. Academic support. Special education advocacy. Liaison between families, schools, commanders, and installation programs.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "survivor-benefits-and-ltap",
    label: "Survivor Benefits and Long Term Assistance Program (LTAP)",
    shortLabel: "Survivor Benefits / LTAP",
    description: "Long Term Assistance Program (LTAP) at HQMC. Indefinite assistance to next of kin of deceased Marines. Magellan Federal benefits printout. Gold Star and Surviving Family Member Representatives. Benevolent and philanthropic organization connections. 866-210-3421 ext 2 or LTAP@usmc.mil.",
    icon: "Users",
    pageType: "leaf",
  },
  {
    slug: "records-and-personal-data",
    label: "Records and Personal Data",
    shortLabel: "Records",
    description: "Your OMPF, MCTFS record, and Marine Online review responsibilities. Catching record errors before they cost you at a promotion or selection board.",
    icon: "FileText",
    pageType: "container",
  },
];

export function findMarinesCategory(slug: string): MarinesCategory | undefined {
  return MARINES_CATEGORIES.find((c) => c.slug === slug);
}

/**
 * Parent group definitions. A parent group consolidates multiple
 * MarinesCategory entries under a single landing page. The main /marines
 * page renders parent group cards in place of the individual child topic
 * cards, and a parent landing page at /marines/[group-slug] lists the
 * children. Existing topic URLs (/marines/[topic-slug]) keep working.
 */
export interface MarinesParentGroup {
  slug: string;
  label: string;
  shortLabel: string;
  description: string;
  icon: MarinesCategory["icon"];
  /** Slugs of MarinesCategory items grouped under this parent. */
  children: string[];
}

export const MARINES_PARENT_GROUPS: MarinesParentGroup[] = [
  {
    slug: "artificial-intelligence",
    label: "Artificial Intelligence (AI)",
    shortLabel: "AI",
    description:
      "Marine Corps data and AI framework. MCO 5231.4 governance. DC I as service lead. Service Data Office (SDO). Mandatory Basic AI Course. GenAI.mil platform. NPS AI Fellowship. Responsible AI principles. Per MCO 5231.4 and MARADMIN ecosystem (214/26, 635/24, 270/25, 018/26, 135/26).",
    icon: "Star",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "ai-and-data-management-training",
      "ai-ethical-use",
      "ai-fellowship-programs",
      "ai-governance-and-approval",
      "ai-overview",
      "basic-ai-course",
      "camogpt-and-approved-ai-tools",
      "data-and-ai-workforce-roles",
      "genai-mil-enterprise-platform",
      "practical-ai-use",
      "semper-admin-ai-field-manual",
    ],
  },
  {
    slug: "awards",
    label: "Awards",
    shortLabel: "Awards",
    description:
      "Personal Military Decorations (PMDs), unit awards, foreign awards, joint service awards, marksmanship badges, campaign and service medals. Submission, ceremony, OMPF verification. Per MCO P1650.19J.",
    icon: "Trophy",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "awards-overview",
      "campaign-and-service-medals",
      "combat-action-ribbon",
      "foreign-awards",
      "joint-service-awards",
      "marksmanship-badges",
      "movsm",
      "pcs-and-awards-timing",
      "personal-military-decorations",
      "purple-heart",
      "receiving-an-award",
      "retirement-awards-and-dd214",
      "unit-awards",
      "verifying-your-awards",
      "wearing-your-awards",
    ],
  },
  {
    slug: "pay-and-entitlements",
    label: "Pay and Entitlements",
    shortLabel: "Pay & Entitlements",
    description:
      "Basic pay, BAH, BAS, deployment pays, special pays, and pay problems. Everything in your LES.",
    icon: "DollarSign",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "advance-and-emergency-pay",
      "allotments",
      "assignment-incentive-pay",
      "aviation-bonus",
      "aviation-incentive-pays",
      "bah",
      "bankruptcy-and-pay",
      "bas",
      "basic-needs-allowance",
      "basic-pay",
      "career-sea-pay",
      "clothing-monetary-allowances",
      "combat-zone-tax-exclusion",
      "comparable-grades",
      "continuation-pay",
      "conus-cola",
      "court-martial-and-njp-pay-impact",
      "death-payments",
      "diving-duty-pay",
      "enlisted-bonuses",
      "family-separation-allowance",
      "federal-tax-withholding",
      "fica-and-afrh-deductions",
      "flexible-spending-accounts",
      "foreign-language-proficiency-bonus",
      "hardship-duty-pay",
      "hazardous-duty-incentive-pay",
      "health-professions-officer-pays",
      "high-deployment-allowance",
      "hostile-fire-and-imminent-danger-pay",
      "illness-or-injury-payments",
      "oconus-cola",
      "oconus-tour-extension-incentive",
      "officer-bonuses",
      "officers-uniform-and-equipment-allowance",
      "pay-problems-and-fixes",
      "priority-of-pay-deductions",
      "reserve-pay-and-entitlements",
      "separation-payments",
      "sgli-and-vgli",
      "special-duty-assignment-pay",
      "tsp-and-savings",
      "volunteer-supplemental-incentive",
    ],
  },
  {
    slug: "leave-and-liberty",
    label: "Leave and Liberty",
    shortLabel: "Leave",
    description:
      "Annual leave, SLA, liberty, parental leave, PTAD, foreign leave, terminal leave, and other absence types.",
    icon: "CalendarDays",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "advance-and-excess-leave",
      "annual-leave",
      "appellate-leave",
      "convalescent-leave",
      "emergency-leave",
      "foreign-leave",
      "leave-problems-and-fixes",
      "leave-submission-and-administration",
      "liberty-and-special-liberty",
      "military-parental-leave-program",
      "permissive-tad",
      "reserve-maternity-leave",
      "reserve-parental-leave",
      "rr-and-srr-leave-programs",
      "special-leave-accrual",
      "terminal-leave",
    ],
  },
  {
    slug: "pcs",
    label: "Permanent Change of Station (PCS)",
    shortLabel: "PCS",
    description:
      "Orders, member and dependent travel, HHG, POV shipment, allowances (DLA, TLE, MEA), tax adjustments, and special PCS conditions.",
    icon: "Truck",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "childcare-provider-travel",
      "dislocation-allowance",
      "household-goods-and-ppm",
      "human-breast-milk-shipment",
      "joining-a-unit",
      "member-and-dependent-travel",
      "miscellaneous-expense-allowance",
      "pcs-orders-and-overview",
      "pcs-per-diem",
      "pcs-with-tdy-en-route",
      "pet-transportation-allowance",
      "pov-shipment-and-mileage",
      "renewal-agreement-travel",
      "separation-retirement-accession-travel",
      "temporary-lodging-expense",
    ],
  },
  {
    slug: "tad",
    label: "TDY/TAD (Temporary Duty)",
    shortLabel: "TDY/TAD",
    description:
      "TDY orders, per diem, lodging, transportation, DTS, GTCC, vouchers, long-term TDY, and reimbursement.",
    icon: "Briefcase",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "long-term-tdy",
      "tdy-lodging",
      "tdy-per-diem",
      "tdy-tad-overview",
      "tdy-transportation",
      "travel-vouchers-and-reimbursement",
    ],
  },
  {
    slug: "gtcc",
    label: "Government Travel Charge Card (GTCC)",
    shortLabel: "GTCC",
    description:
      "Cardholder-focused GTCC program. Apply, manage account, split disbursement, GTCC use during PCS and TDY, misuse and suspension. Per DoDI 5154.31 Vol 4, MCO 4600.40C, and MARADMIN 478/24.",
    icon: "CreditCard",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "apply-for-gtcc",
      "gtcc-account-management",
      "gtcc-misuse-and-suspension",
      "gtcc-overview",
      "gtcc-pcs-use",
      "gtcc-split-disbursement",
      "gtcc-tdy-use",
      "standard-vs-restricted-iba",
    ],
  },
  {
    slug: "dts",
    label: "Defense Travel System (DTS)",
    shortLabel: "DTS",
    description:
      "Traveler-focused DTS program. Profile setup, creating authorizations, submitting vouchers, trip cancellations, OTOs and zero-dollar vouchers, voucher approval routing, IDT travel reimbursement. Per MCO 4650.39A, MARADMIN 359/25, MARADMIN 291/12, MARADMIN 157/25.",
    icon: "Plane",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "creating-dts-authorizations",
      "dts-outstanding-travel-orders",
      "dts-overview",
      "dts-profile-and-setup",
      "dts-roles-and-routing",
      "dts-voucher-approval-process",
      "idt-travel-reimbursement",
      "submitting-dts-vouchers",
      "dts-trip-cancellations",
    ],
  },
  {
    slug: "education",
    label: "Education",
    shortLabel: "Education",
    description:
      "Marine Corps voluntary education. Tuition Assistance (TA), Post-9/11 GI Bill, Montgomery GI Bill, MarineNet, Marine Corps University, JPME, civilian degree pursuit, DANTES testing. Per MCO 1560.25, 38 USC Chapter 33, 38 USC Chapter 30, and 10 USC Chapter 1606.",
    icon: "GraduationCap",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "civilian-degree-pursuit",
      "dantes-testing",
      "education-overview",
      "education-at-transition",
      "joint-professional-military-education",
      "marine-corps-university",
      "marinenet-and-distance-learning",
      "montgomery-gi-bill",
      "post-9-11-gi-bill",
      "tuition-assistance",
    ],
  },
  {
    slug: "performance-evaluation",
    label: "Performance Evaluation (FITREP and JEPES)",
    shortLabel: "Performance Evaluation",
    description:
      "Marine Corps performance evaluation framework. FITREPs for Sergeants and above (MCO 1610.7B), JEPES for E-1 through E-4 (MCO 1616.1), body composition reporting (MARADMIN 066/26), MRO/RS/RO chain, PERB appeals, Master Brief Sheet.",
    icon: "ClipboardList",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "apes-and-fitrep-administration",
      "academic-fitreps",
      "adverse-fitreps",
      "body-composition-reporting",
      "fitrep-appeals-perb",
      "fitrep-reporting-cycle",
      "fitrep-sections-and-marking",
      "jepes-junior-enlisted",
      "master-brief-sheet",
      "performance-evaluation-overview",
      "reporting-senior-and-reviewing-officer-roles",
    ],
  },
  {
    slug: "legal-services",
    label: "Legal Services",
    shortLabel: "Legal",
    description:
      "Marine-focused legal topics. JAG services, Article 31 rights, NJP, court-martial, administrative separation, powers of attorney and wills, SCRA, family law, complaints, sexual assault reporting, claims, foreign jurisdiction. Per MCO 5800.16 (LEGADMINMAN) Vols 1-17 and JAGMAN.",
    icon: "LifeBuoy",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "administrative-separation",
      "article-138-and-ig-complaints",
      "article-31-rights-and-investigations",
      "court-martial-process",
      "family-law-for-marines",
      "foreign-jurisdiction-sofa",
      "legal-services-overview",
      "njp-non-judicial-punishment",
      "personal-property-claims",
      "powers-of-attorney-and-wills",
      "servicemembers-civil-relief-act",
      "sexual-assault-reporting-svc",
    ],
  },
  {
    slug: "promotions",
    label: "Promotions",
    shortLabel: "Promotions",
    description:
      "Officer and enlisted promotion framework. Junior enlisted (JEPES), SULI, SNCO selection boards, officer promotion boards, meritorious promotions, PME, OBS, delays/revocations, remedial selection, failure of selection. Per MCO P1400.32D, MCO 1400.31D, MARADMIN 225/23, MCO 5420.16D.",
    icon: "TrendingUp",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "failure-of-selection",
      "junior-enlisted-promotions",
      "meritorious-promotions",
      "non-competitive-cpl-to-sgt-promotions",
      "obligated-service-for-promotion",
      "officer-promotion-boards",
      "pme-requirements-for-promotion",
      "promotion-delays-and-revocations",
      "promotions-overview",
      "remedial-selection",
      "selection-board-preparation",
      "snco-selection-boards",
    ],
  },
  {
    slug: "separations-and-retirement",
    label: "Separations and Retirement",
    shortLabel: "Sep / Ret",
    description:
      "Lifecycle framework for separating and retiring Marines. Voluntary and involuntary separations. Active duty retirement (length of service, TERA). Reserve retirement (qualifying years, points, reduced age, RCSBP). Disability Evaluation System and limited duty. Per MCO 1900.16 (MARCORSEPMAN), 10 USC 12731-12732, NDAA, MMSR sections.",
    icon: "LogOut",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "disability-evaluation-system",
      "involuntary-separations",
      "limited-duty",
      "reserve-component-survivor-benefit-plan",
      "reserve-retirement",
      "retired-pay-and-sbp",
      "retirement-timeline",
      "retirement-types-and-eligibility",
      "separation-pay-and-final-pay",
      "separations-and-retirement-overview",
      "spd-and-re-codes",
      "transition-requirements",
      "voluntary-separations",
    ],
  },
  {
    slug: "reenlistments-and-extensions",
    label: "Reenlistments and Extensions",
    shortLabel: "Reenlistments",
    description:
      "Career continuation framework. FTAP, STAP, ECDP, CRP, CGRP, DSI, EDSI, SRB, kickers, LATMOV, extensions, DAP. Per MCO 1040.31, MARADMIN 590/25 (FY27 Retention), MARADMIN 023/26 (FY27 SRB), MARADMIN 076/25 (ECDP), MCO 7220.24P.",
    icon: "RefreshCcw",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "boatspaces-and-allocations",
      "career-reenlistments-stap",
      "direct-affiliation-program",
      "duty-station-incentive",
      "extensions",
      "first-term-reenlistments-ftap",
      "lateral-moves-program",
      "reenlistment-eligibility-and-process",
      "reenlistments-and-extensions-overview",
      "selective-retention-bonus-and-targeted-mos",
    ],
  },
  {
    slug: "life-events",
    label: "Life Events (Dependent Add and Loss)",
    shortLabel: "Life Events",
    description:
      "Marriage, birth, divorce, death, custody. Secondary dependency (DD 137). Family Care Plan. DEERS, ID cards, NAVMC 10922, dependency validation. Per MCO 1751.3, MCO 1740.13, DoD 7000.14-R Volume 7A Chapter 26.",
    icon: "Heart2",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "birth-and-adoption",
      "child-custody-changes",
      "death-of-dependent",
      "deers-enrollment-and-id-cards",
      "dependency-validation-and-recertification",
      "divorce-and-spouse-loss",
      "family-care-plan",
      "life-events-overview",
      "marriage-and-spouse-add",
      "secondary-dependency-dd-137",
    ],
  },
  {
    slug: "marine-and-family-programs",
    label: "Marine and Family Programs (MF)",
    shortLabel: "Marine & Family",
    description:
      "MF Branch at HQMC. Casualty Assistance Program (CACO, LTAP, Gold Star, Funeral Honors, Repatriation, Investigation Tracking). EFMP, CYP, SLP. Family Readiness (UPFRP, MCFTB, IR&R, Sponsorship). PFMP. Career Services (FMEAP, COOL, USMAP). Education and Resilience (LSP, VolEd, Library, CREDO, Marine for Life). Per MCO 1754.9, MCO 1770.1, MCO 3040.4, MCO 1740.13, and Marine Corps Community Services policy.",
    icon: "Users",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "career-services",
      "casualty-assistance-program",
      "casualty-investigation-tracking",
      "child-and-youth-programs",
      "education-services-and-resilience",
      "exceptional-family-member-program",
      "family-readiness-services",
      "marine-and-family-programs-overview",
      "military-funeral-honors-and-repatriation",
      "personal-financial-management-program",
      "school-liaison-program",
      "survivor-benefits-and-ltap",
    ],
  },
  {
    slug: "strategic-location-incentive-program",
    label: "Strategic Location Incentive Program (SLIP)",
    shortLabel: "SLIP",
    description:
      "Career Marines volunteering for difficult-to-fill assignments earn the right to choose their follow-on duty station. MARADMIN 470/24. MOS-specific eligible locations. Zones B/C/D reenlistment, valid RE code, not HSST-screened, time-on-station requirement met.",
    icon: "Plane",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "slip-duty-station-incentive",
      "slip-eligible-billets-by-mos",
    ],
  },
  {
    slug: "records-and-personal-data",
    label: "Records and Personal Data",
    shortLabel: "Records",
    description:
      "Your OMPF, MCTFS record, and Marine Online review responsibilities. Catching record errors before they cost you at a promotion or selection board.",
    icon: "FileText",
    // Children listed in alphabetical order by label (case-insensitive).
    children: [
      "records-and-personal-data",
    ],
  },
];

export function findMarinesParentGroup(
  slug: string
): MarinesParentGroup | undefined {
  return MARINES_PARENT_GROUPS.find((g) => g.slug === slug);
}

/**
 * Returns the MarinesCategory entries belonging to a parent group, in the
 * order specified by the group's children array.
 */
export function getCategoriesForGroup(groupSlug: string): MarinesCategory[] {
  const group = findMarinesParentGroup(groupSlug);
  if (!group) return [];
  return group.children
    .map((s) => findMarinesCategory(s))
    .filter((c): c is MarinesCategory => c !== undefined);
}

/**
 * Returns the MarinesCategory entries that are not consolidated under
 * any parent group. The main /marines page renders these as individual
 * cards alongside the parent-group cards.
 */
export function getUngroupedCategories(): MarinesCategory[] {
  const groupedSlugs = new Set(
    MARINES_PARENT_GROUPS.flatMap((g) => g.children)
  );
  return MARINES_CATEGORIES.filter((c) => !groupedSlugs.has(c.slug));
}

/**
 * Returns the parent group a given category belongs to, or undefined if
 * the category is not consolidated under any parent group. Used by the
 * breadcrumb on leaf-topic and grouped-topic pages to show the parent
 * group as the second segment (e.g., Marines > Pay and Entitlements > Basic Pay).
 */
export function findParentGroupForCategory(
  categorySlug: string
): MarinesParentGroup | undefined {
  return MARINES_PARENT_GROUPS.find((g) => g.children.includes(categorySlug));
}
