version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "deps"
    groups:
      dependencies:
        patterns:
          - "*"
    allow:
      - dependency-type: "production"
      - dependency-type: "dev"
