"use client";

import { TabbedContentLayout } from "../ui/TabbedContentLayout";
import { InfoCard } from "../ui/InfoCard";
import { FlaskConical, AlertTriangle, Clock, Eye } from "lucide-react";

interface Reference {
  title: string;
  url: string;
  isQuickLink?: boolean;
}

interface Props {
  data: {
    references: Reference[];
  };
}

const TABS = [
  { id: "overview", label: "Overview" },
  { id: "codes", label: "Testing Codes" },
  { id: "process", label: "Process" },
  { id: "issues", label: "Common Issues" },
  { id: "references", label: "References", type: "references" as const },
];

const KEY_POINTS = [
  { label: "Random (IR)", value: "Generated by software (iFAMS/DTP); ensures equal chance of testing" },
  { label: "Command Directed (CO)", value: "Used with credible information but not probable cause; results usually administrative only" },
  { label: "Probable Cause (PO)", value: "Requires consultation with Judge Advocate and formal search authorization signed by CO" },
  { label: "Monthly Requirement", value: "Commands must test at least 10% of total population per month" },
];

const TESTING_CODES = [
  { code: "IR", description: "Random (Computer)", purpose: "Deterrence", admissibility: "Yes" },
  { code: "CO", description: "Command Directed", purpose: "Safety/Readiness", admissibility: "Limited" },
  { code: "PO", description: "Probable Cause", purpose: "Criminal Inquiry", admissibility: "Yes" },
  { code: "VO", description: "Voluntary", purpose: "Consent", admissibility: "Yes" },
];

const PROCESS_STEPS = [
  "Selection: UUC generates the list via approved software (iFAMS/DTP)",
  "Notification: Marines are notified and must remain under observation until sample provided",
  "Observation: Observers (same gender) must have direct line of sight on 'bottle-to-body' connection",
  "Collection: Sample provided, sealed, and documented per chain of custody procedures",
  "Logging: Samples are logged with correct testing code and Marine's information",
  "Shipping: Samples boxed and shipped to Navy Drug Screening Laboratory (NDSL)",
];

const TIMELINE_REQUIREMENTS = [
  { requirement: "Monthly", action: "Test at least 10% of total unit population" },
  { requirement: "48 Hours", action: "Samples should ideally be shipped within 48 hours of collection" },
  { requirement: "Continuous", action: "Maintain observation from notification until sample provided" },
];

const OBSERVER_REQUIREMENTS = [
  "Same gender as the Marine providing the sample",
  "Direct line of sight on 'bottle-to-body' connection",
  "Cannot be distracted or look away during collection",
  "Must be trained on proper observation procedures",
  "Document any issues or anomalies immediately",
];

const COMMON_ISSUES = [
  {
    issue: "Observer failure",
    solution: "Observers failing to actually maintain visual contact with the sample being provided. This is the #1 reason NJPs are overturned on appeal. Train observers thoroughly and verify compliance.",
  },
  {
    issue: "Wrong testing code",
    solution: "Using incorrect basis code on the ledger, which can affect admissibility at court-martial. Verify the correct code with SACO and legal before collection.",
  },
  {
    issue: "Delayed shipping",
    solution: "Samples sitting for extended periods before shipment can raise chain of custody concerns. Ship within 48 hours of collection.",
  },
];

export function TestingRequirementsContent({ data }: Props) {
  const content: Record<string, React.ReactNode> = {
    overview: (
      <div className="space-y-6">
        <InfoCard icon={FlaskConical} title="Urinalysis Testing Requirements" variant="info">
          The Marine Corps uses urinalysis as a <strong>deterrent and detection tool</strong>.
          There are several &quot;basis&quot; types for testing, and the Commander must ensure
          the correct code is used on the ledger to protect the legal integrity of the sample.
        </InfoCard>

        <section className="rounded-xl border border-black/5 bg-white p-6 shadow-sm dark:border-white/15 dark:bg-black/40">
          <h2 className="text-xl font-semibold text-[var(--sa-navy)] dark:text-[var(--sa-cream)]">
            Key Points
          </h2>
          <div className="mt-4 overflow-x-auto">
            <table className="min-w-full text-sm">
              <tbody>
                {KEY_POINTS.map((point) => (
                  <tr key={point.label} className="border-b border-zinc-100 dark:border-zinc-800">
                    <td className="py-3 pr-4 font-medium text-zinc-700 dark:text-zinc-300">{point.label}</td>
                    <td className="py-3 text-zinc-600 dark:text-zinc-400">{point.value}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="rounded-xl border border-black/5 bg-white p-6 shadow-sm dark:border-white/15 dark:bg-black/40">
          <h3 className="text-lg font-semibold text-[var(--sa-navy)] dark:text-[var(--sa-cream)]">
            Timeline Requirements
          </h3>
          <div className="mt-4 overflow-x-auto">
            <table className="min-w-full text-sm">
              <thead>
                <tr className="border-b border-zinc-200 dark:border-zinc-700">
                  <th className="py-2 pr-4 text-left font-semibold text-zinc-900 dark:text-zinc-100">Requirement</th>
                  <th className="py-2 text-left font-semibold text-zinc-900 dark:text-zinc-100">Action</th>
                </tr>
              </thead>
              <tbody>
                {TIMELINE_REQUIREMENTS.map((item) => (
                  <tr key={item.requirement} className="border-b border-zinc-100 dark:border-zinc-800">
                    <td className="py-3 pr-4 font-medium text-zinc-700 dark:text-zinc-300">{item.requirement}</td>
                    <td className="py-3 text-zinc-600 dark:text-zinc-400">{item.action}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <InfoCard icon={Clock} title="10% Monthly Minimum" variant="warning">
          Commands must test at least <strong>10% of their total population</strong>
          per month. Track testing rates to ensure compliance.
        </InfoCard>
      </div>
    ),

    codes: (
      <div className="space-y-6">
        <section className="rounded-xl border border-black/5 bg-white p-6 shadow-sm dark:border-white/15 dark:bg-black/40">
          <h2 className="text-xl font-semibold text-[var(--sa-navy)] dark:text-[var(--sa-cream)]">
            Testing Codes
          </h2>
          <div className="mt-4 overflow-x-auto">
            <table className="min-w-full text-sm">
              <thead>
                <tr className="border-b border-zinc-200 dark:border-zinc-700">
                  <th className="py-2 pr-4 text-left font-semibold text-zinc-900 dark:text-zinc-100">Code</th>
                  <th className="py-2 pr-4 text-left font-semibold text-zinc-900 dark:text-zinc-100">Description</th>
                  <th className="py-2 pr-4 text-left font-semibold text-zinc-900 dark:text-zinc-100">Purpose</th>
                  <th className="py-2 text-left font-semibold text-zinc-900 dark:text-zinc-100">Court-Martial</th>
                </tr>
              </thead>
              <tbody>
                {TESTING_CODES.map((code) => (
                  <tr key={code.code} className="border-b border-zinc-100 dark:border-zinc-800">
                    <td className="py-3 pr-4 font-mono font-bold text-zinc-900 dark:text-zinc-100">{code.code}</td>
                    <td className="py-3 pr-4 text-zinc-700 dark:text-zinc-300">{code.description}</td>
                    <td className="py-3 pr-4 text-zinc-600 dark:text-zinc-400">{code.purpose}</td>
                    <td className="py-3 text-zinc-600 dark:text-zinc-400">{code.admissibility}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <InfoCard icon={AlertTriangle} title="Probable Cause (PO) Requirements" variant="warning">
          Probable Cause testing requires <strong>consultation with a Judge Advocate</strong>
          and a formal search authorization signed by the CO. Do not use PO code without
          legal coordination.
        </InfoCard>

        <section className="rounded-xl border border-black/5 bg-white p-6 shadow-sm dark:border-white/15 dark:bg-black/40">
          <h3 className="text-lg font-semibold text-[var(--sa-navy)] dark:text-[var(--sa-cream)]">
            Code Selection Guidance
          </h3>
          <ul className="mt-3 space-y-2 text-sm text-zinc-600 dark:text-zinc-400">
            <li>&bull; <strong>IR:</strong> Standard random testing—use for routine deterrence</li>
            <li>&bull; <strong>CO:</strong> When you have suspicion but not probable cause—consult SACO</li>
            <li>&bull; <strong>PO:</strong> When you have reasonable belief—consult legal first</li>
            <li>&bull; <strong>VO:</strong> When Marine volunteers to be tested</li>
          </ul>
        </section>
      </div>
    ),

    process: (
      <div className="space-y-6">
        <section className="rounded-xl border border-black/5 bg-white p-6 shadow-sm dark:border-white/15 dark:bg-black/40">
          <h2 className="text-xl font-semibold text-[var(--sa-navy)] dark:text-[var(--sa-cream)]">
            Testing Process
          </h2>
          <div className="mt-6 space-y-4">
            {PROCESS_STEPS.map((step, index) => (
              <div key={step} className="flex items-start gap-4">
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[var(--sa-navy)] text-sm font-bold text-white">
                  {index + 1}
                </span>
                <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">{step}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="rounded-xl border border-black/5 bg-white p-6 shadow-sm dark:border-white/15 dark:bg-black/40">
          <h3 className="text-lg font-semibold text-[var(--sa-navy)] dark:text-[var(--sa-cream)]">
            Observer Requirements
          </h3>
          <ul className="mt-4 space-y-2">
            {OBSERVER_REQUIREMENTS.map((req) => (
              <li key={req} className="flex items-start gap-2 text-sm text-zinc-600 dark:text-zinc-400">
                <span className="mt-1 h-2 w-2 rounded-full bg-[var(--sa-navy)]" />
                {req}
              </li>
            ))}
          </ul>
        </section>

        <InfoCard icon={Eye} title="Bottle-to-Body Observation" variant="warning">
          Observers must maintain <strong>direct line of sight</strong> on the
          &quot;bottle-to-body&quot; connection. This is the #1 reason positive results
          are overturned on appeal.
        </InfoCard>
      </div>
    ),

    issues: (
      <div className="space-y-6">
        <section className="rounded-xl border border-black/5 bg-white p-6 shadow-sm dark:border-white/15 dark:bg-black/40">
          <h2 className="text-xl font-semibold text-[var(--sa-navy)] dark:text-[var(--sa-cream)]">
            Common Problems & Solutions
          </h2>
          <div className="mt-4 space-y-4">
            {COMMON_ISSUES.map((item) => (
              <div key={item.issue} className="rounded-lg border-l-4 border-amber-500 bg-amber-50 p-4 dark:bg-amber-900/20">
                <h4 className="font-medium text-amber-800 dark:text-amber-200">Problem: {item.issue}</h4>
                <p className="mt-2 text-sm text-amber-700 dark:text-amber-300">
                  <strong>Solution:</strong> {item.solution}
                </p>
              </div>
            ))}
          </div>
        </section>
      </div>
    ),
  };

  return <TabbedContentLayout tabs={TABS} data={data} content={content} />;
}
